In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("Fish.csv")

In [3]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
data['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['Species'] = label_encoder.fit_transform(data['Species'])

In [9]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    int32  
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), int32(1)
memory usage: 8.2 KB


In [11]:
x=data.iloc[:,1:7].values
y=data.iloc[:,0:1].values


In [12]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [13]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
    

In [14]:
y.dtype

dtype('int32')

In [15]:
x.shape

(159, 6)

In [16]:
y.shape

(159, 1)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


# Model Building

In [19]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [20]:
model = Sequential()

In [21]:
x.shape

(159, 6)

In [22]:
model.add(Dense(units = 6,kernel_initializer = 'random_uniform',activation = 'relu')) #input layer

In [23]:
model.add(Dense(units =12,kernel_initializer = 'random_uniform',activation = 'relu')) # 1st hidden layer

In [24]:
model.add(Dense(units = 7 ,kernel_initializer = 'random_uniform',activation = 'softmax')) #Output Layer

In [25]:
model.compile (optimizer = 'adam',loss = 'sparse_categorical_crossentropy',metrics = ['accuracy'])

In [26]:
model.fit(x_train,y_train , batch_size = 32,epochs = 300)

Epoch 1/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1360 - loss: 1.9453  
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2989 - loss: 1.9426 
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3678 - loss: 1.9398 
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3824 - loss: 1.9373 
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3689 - loss: 1.9343 
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3897 - loss: 1.9307 
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3866 - loss: 1.9267 
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3324 - loss: 1.9236 
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3491 - loss: 1.9183 
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3991 - loss: 1.9121 
Epoch 11/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3949 - loss: 1.9028 
Epoch 12/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3834 - lo

In [27]:
y_pred = model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


In [28]:
y_pred #Predicted Value

array([[7.96165645e-01, 6.66924044e-02, 8.13887939e-02, 3.27526480e-02,
        6.11583749e-03, 8.82258428e-06, 1.68758258e-02],
       [4.67764103e-08, 6.97811916e-02, 5.52056015e-01, 7.19068227e-09,
        2.31147081e-01, 1.45699009e-01, 1.31668383e-03],
       [2.75272782e-07, 5.85284792e-02, 5.74246109e-01, 1.02868810e-07,
        2.50791728e-01, 1.13934338e-01, 2.49899109e-03],
       [1.15953446e-06, 9.42937657e-02, 5.80047429e-01, 2.53412367e-07,
        2.38417208e-01, 8.34653005e-02, 3.77483619e-03],
       [2.88210392e-01, 6.30584508e-02, 2.91863769e-01, 2.56053001e-01,
        4.27085347e-02, 1.80200528e-04, 5.79255968e-02],
       [3.13305885e-01, 2.83964854e-02, 3.22083145e-01, 2.93446749e-01,
        1.53227011e-02, 5.86587066e-06, 2.74391975e-02],
       [4.44723904e-01, 4.44076695e-02, 2.60917753e-01, 2.01765373e-01,
        1.66574474e-02, 1.30547978e-05, 3.15147638e-02],
       [3.87921333e-02, 9.96071175e-02, 6.03416979e-01, 5.20450100e-02,
        1.33483410e-01, 1

In [29]:
y_test.flatten() #Actual Value

array([0, 4, 2, 4, 2, 2, 6, 3, 0, 2, 3, 3, 6, 2, 1, 4, 4, 3, 2, 0, 1, 4,
       2, 3, 1, 0, 0, 6, 2, 5, 0, 2])

In [30]:
y_test[0]

array([0])

In [31]:
y_pred[0]

array([7.9616565e-01, 6.6692404e-02, 8.1388794e-02, 3.2752648e-02,
       6.1158375e-03, 8.8225843e-06, 1.6875826e-02], dtype=float32)

In [32]:
output=np.argmax(y_pred[0])

In [33]:
output

0

In [34]:
data.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0        0   242.0     23.2     25.4     30.0   11.52   4.02

In [35]:
y_p = model.predict((sc.transform([[242,23.2,23,30,11,4]])))
                    

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


In [36]:
y_p

array([[0.03273408, 0.5090152 , 0.32631528, 0.00110961, 0.08281463,
        0.00279495, 0.04521631]], dtype=float32)

In [37]:
index = ['Bream', 'Parkki','Perch','Pike','Roach', 'Smelt','Whitefish']

In [38]:
p=np.argmax(y_p)

In [39]:
p

1

In [40]:
index[p]

'Parkki'