# *SVM Classification on Breastcancer data*

In [1]:
#Importing the lIbraries
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('breast_cancer.csv')
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  outcome  
0          0.4601                  0.11890        1  
1          0.2750                  0.08902        1  
2          0.3613                  0.08758        1  
3          0.6638                  0.17300        1  
4          0.2364                  0.07678        1  

[5 rows x 31 columns]

In [3]:
df.shape

(569, 31)

In [4]:
df.outcome.value_counts()

outcome
0    357
1    212
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [6]:
X=df.iloc[:, : -1]
y=df.outcome

In [7]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [8]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: outcome, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=47)

## *train model*

In [10]:
from sklearn.svm import SVC

model= SVC()

In [11]:
model.fit(X_train,y_train)

SVC()

In [12]:
y_predict=model.predict(X_test)
y_predict

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0], dtype=int64)

In [13]:
y_pred_train=model.predict(X_train)
y_pred_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,

In [14]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
accuracy_score(y_test,y_predict)

0.9122807017543859

In [16]:
accuracy_score(y_train,y_pred_train)

0.9230769230769231

In [17]:
confusion_matrix(y_test,y_predict)

array([[67,  3],
       [ 7, 37]], dtype=int64)

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.91      0.96      0.93        70
           1       0.93      0.84      0.88        44

    accuracy                           0.91       114
   macro avg       0.92      0.90      0.91       114
weighted avg       0.91      0.91      0.91       114



# *Hyper parameter Tuning*

## *Gridsearch CV*

In [19]:
from sklearn.model_selection import GridSearchCV

In [23]:
parameters={
    'kernel':['linear','rbf'],
    'C':[0.1,0.5,1.0],
    'gamma':[0.01,0.0001]
}
clf = GridSearchCV(SVC(), param_grid=parameters,verbose=3)

clf.fit(X_train,y_train)


Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.956 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.934 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.989 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.945 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.923 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.626 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.626 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.626 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.637 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.637 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.956 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.0001, kernel=linear;

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 0.5, 1.0], 'gamma': [0.01, 0.0001],
                         'kernel': ['linear', 'rbf']},
             verbose=3)

In [24]:
clf.best_score_

0.9604395604395604

In [25]:
clf.best_params_

{'C': 1.0, 'gamma': 0.01, 'kernel': 'linear'}

## *Best Parameters are found*

In [26]:
model2= SVC(C=1, gamma=0.01, kernel='linear')

model2.fit(X_train,y_train)

SVC(C=1, gamma=0.01, kernel='linear')

In [27]:
y_predict=model2.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,classification_report

In [29]:
accuracy_score(y_test,y_predict)

0.956140350877193

In [30]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      0.94      0.96        70
           1       0.91      0.98      0.95        44

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114



In [ ]:
#Similarly for Random

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:

parameters={
    'kernel':['linear','rbf'],
    'C':[0.1,0.5,1.0],
    'gamma':[0.01,0.0001]
}
RCV  = RandomizedSearchCV(estimator=SVC(),param_distributions=parameters,cv=10,n_iter=4,verbose=2)


In [33]:
RCV.fit(X_train,y_train)

Fitting 10 folds for each of 4 candidates, totalling 40 fits
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.5, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01

RandomizedSearchCV(cv=10, estimator=SVC(), n_iter=4,
                   param_distributions={'C': [0.1, 0.5, 1.0],
                                        'gamma': [0.01, 0.0001],
                                        'kernel': ['linear', 'rbf']},
                   verbose=2)

In [34]:
RCV.best_score_

0.9406280193236716

In [35]:
RCV.best_params_

{'kernel': 'linear', 'gamma': 0.01, 'C': 0.1}

In [36]:
model3= SVC(C=1, gamma=0.0001, kernel='linear')

model3.fit(X_train,y_train)

SVC(C=1, gamma=0.0001, kernel='linear')

In [37]:
y_predict2=model3.predict(X_test)

In [38]:
accuracy_score(y_test,y_predict2)

0.956140350877193