In [1]:
# import required libraries
import pandas as pd
import numpy as np

In [2]:
# Reading the dataset
df = pd.read_csv('50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.shape

(50, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [6]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [8]:
df['State'] = le.fit_transform(df.State)

In [9]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [10]:
X =df.iloc[:,:-1].values

In [11]:
y= df.iloc[:,4:5].values

In [38]:
from sklearn.preprocessing import StandardScaler

In [40]:
scale = StandardScaler()

In [41]:
X = scale.fit_transform(X)

In [42]:
X

array([[ 2.01641149e+00,  5.60752915e-01,  2.15394309e+00,
         1.21267813e+00],
       [ 1.95586034e+00,  1.08280658e+00,  1.92360040e+00,
        -1.21267813e+00],
       [ 1.75436374e+00, -7.28257028e-01,  1.62652767e+00,
         0.00000000e+00],
       [ 1.55478369e+00, -9.63646307e-02,  1.42221024e+00,
         1.21267813e+00],
       [ 1.50493720e+00, -1.07991935e+00,  1.28152771e+00,
         0.00000000e+00],
       [ 1.27980001e+00, -7.76239071e-01,  1.25421046e+00,
         1.21267813e+00],
       [ 1.34006641e+00,  9.32147208e-01, -6.88149930e-01,
        -1.21267813e+00],
       [ 1.24505666e+00,  8.71980011e-01,  9.32185978e-01,
         0.00000000e+00],
       [ 1.03036886e+00,  9.86952101e-01,  8.30886909e-01,
         1.21267813e+00],
       [ 1.09181921e+00, -4.56640246e-01,  7.76107440e-01,
        -1.21267813e+00],
       [ 6.20398248e-01, -3.87599089e-01,  1.49807267e-01,
         0.00000000e+00],
       [ 5.93085418e-01, -1.06553960e+00,  3.19833623e-01,
      

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [44]:
x_train.shape, x_test.shape

((40, 4), (10, 4))

In [20]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: C:\Users\Shreesh\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [46]:
regressor = Sequential()

regressor.add(Dense(4,activation='relu'))
regressor.add(Dense(8,activation = 'relu'))
regressor.add(Dense(16,activation = 'relu'))
regressor.add(Dense(1,activation = 'linear'))

In [ ]:
# creating ANN skeleton

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))# input layer
regressor.add(Dense(8,activation='relu')) # first Hidden layer
regressor.add(Dense(16,activation='relu')) # 2nd Hidden layer
regressor.add(Dense(1,activation='linear')) # Output Layer


In [47]:
# Compiling ANN model

regressor.compile(optimizer='adam',loss ='mse',metrics=['mse'] )


In [48]:
# training the model
regressor.fit(x_train,y_train,batch_size=10,epochs =300)


Epoch 1/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 13376043008.0000 - mse: 13376043008.0000
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14598825984.0000 - mse: 14598825984.0000 
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13862341632.0000 - mse: 13862341632.0000 
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13793222656.0000 - mse: 13793222656.0000 
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14145381376.0000 - mse: 14145381376.0000 
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13408667648.0000 - mse: 13408667648.0000 
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13879088128.0000 - mse: 13879088128.0000 
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12388724736.0000 - mse: 12388724736.0000
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13497733120.0000 - mse: 13497733120.0000 
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14120197120.0000 - mse: 14120197120.0000 
Epoch 11/30

In [49]:
# testing the model

y_pred = regressor.predict(x_test)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


In [50]:
y_pred

array([[20571.178],
       [10287.87 ],
       [16542.508],
       [ 6098.213],
       [37059.48 ],
       [27236.281],
       [11637.483],
       [12000.433],
       [19922.006],
       [29292.441]], dtype=float32)

In [51]:
from sklearn.metrics import r2_score

In [52]:
# evaluating the model with r2 score

r2_score(y_test,y_pred)

-8.035274970044398

In [53]:
y_pred.flatten()

array([20571.178, 10287.87 , 16542.508,  6098.213, 37059.48 , 27236.281,
       11637.483, 12000.433, 19922.006, 29292.441], dtype=float32)

In [54]:
# Comparing the actual and predicted y values

pd.DataFrame({'Actual y_value':y_test.flatten(),'Predicted y_value':y_pred.flatten()}).head(10)

Actual y_value  Predicted y_value
0       103282.38       20571.177734
1       144259.40       10287.870117
2       146121.95       16542.507812
3        77798.83        6098.212891
4       191050.39       37059.480469
5       105008.31       27236.281250
6        81229.06       11637.483398
7        97483.56       12000.432617
8       110352.25       19922.005859
9       166187.94       29292.441406

In [ ]:
df.head()

In [ ]:
inputx=np.array([[142107.34,91391.77,366168.42 ,1]])

In [ ]:
# testing with random values

regressor.predict(inputx)